version: "3.8"

services:
    lavalink:
        image: ghcr.io/lavalink-devs/lavalink:latest
        container_name: lavalink
        restart: unless-stopped
        environment:
            - _JAVA_OPTIONS=-Xmx1G
            - SERVER_PORT=2333
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - local
        ports:
            - "2333:2333"

    vocard:
        container_name: vocard
        build:
            dockerfile: ./Dockerfile
        volumes:
            - ./settings.json:/app/settings.json
        depends_on:
            lavalink:
              condition: service_started
        networks:
            - local

networks:
    local:
        name: local
