name: Docker Image CI

on:
  push:
    branches: [ "aio-beta" ]
    paths-ignore:
        - '**.md'

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Convert repository owner to lowercase
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ env.REPO_OWNER }}/miasitas:latest
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker image
      run: docker push ghcr.io/${{ env.REPO_OWNER }}/miasitas:latest